# -*- coding: utf-8 -*-
"""FastFoodAcrossAmerica.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xCfN8KxBkMs7HB0t_YKIQyZVtldsiWA1
"""

from google.colab import files
files.upload()

import numpy as np
import pandas as pd

df = pd.read_csv('Datafiniti_Fast_Food_Restaurants_May19.csv')

df.shape

df.dtypes

df.head()

df = df.drop(['id', 'keys', 'sourceURLs', 'websites'], axis=1)

df.shape

#Checking for duplicated values in dataset
df.duplicated().sum()
#there are no duplicate values

#Checking for null values in dataset
df.isnull().sum()
#there are no null records

