# -*- coding: utf-8 -*-
"""food_code.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13pzYJQQwLWyNNcJZonRBYSvjRyTgb2Yy
"""

from google.colab import files
files.upload()

import numpy as np
import pandas as pd

df = pd.read_csv('food_coded.csv')

df.shape

df.columns

#creating a list of columns which have missing values followed by the number of missing values in each column
mis_clmns = [col for col in df.columns
                     if df[col].isnull().any()]

for i in mis_clmns:
    print(i,df[i].isnull().sum())

df.describe()

#replacing missiing values using fillna() function. 
df['calories_day'].fillna(1,inplace=True)
df['comfort_food_reasons_coded'].fillna(9,inplace=True)
df['cuisine'].fillna(6,inplace=True)
df['employment'].fillna(4,inplace=True)
df['exercise'].fillna(5,inplace=True)
df['type_sports'].fillna('Nothing',inplace=True)

for i in mis_clmns:
    df = df[~df[i].isnull()]

df.shape

#GPA column contains float values in string format along with missing values and bogus values.
#to deal with this,we'll create a new column by first removing the decimal point '.' from the values
df['GPA'].value_counts()

#using value_counts() function to check whether the column values are legit

df['Gender'].value_counts()

df['breakfast'].value_counts()

df['calories_day'] = df['calories_day'].astype(int)
df['calories_day'].value_counts()

df.dropna(subset=['GPA'],inplace=True)
df['GPA_new'] = df['GPA'].str.replace(".","")
df = df[~df['GPA_new'].str.isdigit() == False]
df['GPA'] = df['GPA'].astype(float)
df.drop('GPA_new',axis=1,inplace=True)

#checking duplicate values
df.duplicated().sum()
#there are no duplicate

df.shape

df.head()

#Checking for null values in dataset
df.isnull().sum()
#there are no null records

#to get the unique elements of coffee column
df.coffee.unique()

##to get the unique elements of coffee column
df.breakfast.unique()

#type of data
df.dtypes

df.head()

