# -*- coding: utf-8 -*-
"""Indian Food.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g3qxoAEiRHDyks-mrjnxo80NImOUNlni
"""

from google.colab import files
files.upload()

import numpy as np
import pandas as pd

df = pd.read_csv('indian_food.csv')

df.shape

df.dtypes

df.head()



df.isnull().sum()

df.isna().sum()

df = df.dropna()

df.isnull().sum()

#Checking for duplicated values in dataset
df.duplicated().sum()
#there are no duplicate values

df[df.region=='-1']

df = df.replace(-1,np.NaN)

df.isnull().sum()

df['prep_time'].fillna(df['prep_time'].mean(), inplace = True)
df['cook_time'].fillna(df['cook_time'].mean(), inplace = True)

df.shape

df = df.replace('-1',np.NaN)

df = df.dropna()

df.shape

df.isnull().sum()

