# -*- coding: utf-8 -*-
"""Diabetes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VDo2CwEzSqlLsK8pesMnyozLgJbsdHN_
"""

from google.colab import files
files.upload()

import numpy as np 
import pandas as pd

diabetes_data= pd.read_csv("diabetes.csv")

diabetes_data.head(5)

diabetes_data.columns

diabetes_data.shape

#Checking for duplicated values in dataset
diabetes_data.duplicated().sum()
#there are no duplicate values

#Checking for null values in dataset
diabetes_data.isnull().sum()
#there are no null records

#replace zeros with NaN except columns pregnancies and outcome
diabetes_data[['Glucose','BloodPressure','SkinThickness','Insulin','BMI']] = diabetes_data[['Glucose','BloodPressure','SkinThickness','Insulin','BMI']].replace(0,np.NaN)

diabetes_data.head(5)

diabetes_data.isnull().sum()
#now we can see the null values

#Lets replace the null values with mean for numerical attributes
diabetes_data['Glucose'].fillna(diabetes_data['Glucose'].mean(), inplace = True)
diabetes_data['BloodPressure'].fillna(diabetes_data['BloodPressure'].mean(), inplace = True)
diabetes_data['SkinThickness'].fillna(diabetes_data['SkinThickness'].mean(), inplace = True)
diabetes_data['Insulin'].fillna(diabetes_data['Insulin'].mean(), inplace = True)
diabetes_data['BMI'].fillna(diabetes_data['BMI'].mean(), inplace = True)

diabetes_data.isnull().sum()
#now there are no null values

diabetes_data.head(5)

#Data is cleaned and ready for analysis now!!

