# -*- coding: utf-8 -*-
"""HealthInsurance.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vlk0WN_nrHxHNrGudRtc5WzNRJTVEot7
"""

from google.colab import files
files.upload()

import numpy as np
import pandas as pd

insurance = pd.read_csv("insurance.csv")

insurance.head(5)

insurance.columns

insurance.shape

#Checking for duplicated values in dataset
insurance.duplicated().sum()
#there are no duplicate values

insurance = insurance.drop_duplicates()

insurance.duplicated().sum()

insurance.shape

#Checking for null values in dataset
insurance.isnull().sum()
#there are no null records

insurance.dtypes

insurance['sex'].value_counts()

#The charges column is in object form.
#Replace male with 1 
#        female with 0

insurance['sex']= insurance['sex'].replace('male', 1)
insurance['sex']= insurance['sex'].replace('female', 0)

insurance['smoker'].value_counts()

insurance['smoker']= insurance['smoker'].replace('yes', 1)
insurance['smoker']= insurance['smoker'].replace('no', 0)

insurance.head()



