# -*- coding: utf-8 -*-
"""heart_failure.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B8xV0p-jvVkkPf0rjz2vMgbzyI3xyy5_
"""

from google.colab import files
files.upload()

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('heart_failure_clinical_records_dataset.csv')

df.head()

df.shape

df.isnull().sum()

df.dtypes

df.duplicated().sum()



